<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SL-1549.local" name="com.swaglabs.Tests.LoginInvalidUser" tests="10" failures="2" timestamp="18 Dec 2020 17:34:08 GMT" time="310.364" errors="0">
  <testcase name="LoginInvalidUserTest" time="42.589" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="28.573" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="41.529" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="39.230" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="29.367" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="25.352" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="26.294" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="36.920" classname="com.swaglabs.Tests.LoginInvalidUser"/>
  <testcase name="LoginInvalidUserTest" time="20.240" classname="com.swaglabs.Tests.LoginInvalidUser">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at com.swaglabs.Tests.LoginInvalidUser.LoginInvalidUserTest(LoginInvalidUser.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- LoginInvalidUserTest -->
  <testcase name="LoginInvalidUserTest" time="20.270" classname="com.swaglabs.Tests.LoginInvalidUser">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at com.swaglabs.Tests.LoginInvalidUser.LoginInvalidUserTest(LoginInvalidUser.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- LoginInvalidUserTest -->
</testsuite> <!-- com.swaglabs.Tests.LoginInvalidUser -->
