<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SL-1549.local" name="com.swaglabs.Tests.LoginLockedOutUser" tests="10" failures="2" timestamp="18 Dec 2020 17:34:08 GMT" time="332.078" errors="0">
  <testcase name="LoginLockedOutUserTest" time="19.321" classname="com.swaglabs.Tests.LoginLockedOutUser">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at com.swaglabs.Tests.LoginLockedOutUser.LoginLockedOutUserTest(LoginLockedOutUser.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- LoginLockedOutUserTest -->
  <testcase name="LoginLockedOutUserTest" time="47.664" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="26.740" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="25.776" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="29.402" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="40.050" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="42.283" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="21.756" classname="com.swaglabs.Tests.LoginLockedOutUser">
    <failure type="java.lang.AssertionError" message="">
      <![CDATA[java.lang.AssertionError: 
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:24)
	at org.testng.AssertJUnit.assertTrue(AssertJUnit.java:33)
	at com.swaglabs.Tests.LoginLockedOutUser.LoginLockedOutUserTest(LoginLockedOutUser.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- LoginLockedOutUserTest -->
  <testcase name="LoginLockedOutUserTest" time="39.892" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
  <testcase name="LoginLockedOutUserTest" time="39.194" classname="com.swaglabs.Tests.LoginLockedOutUser"/>
</testsuite> <!-- com.swaglabs.Tests.LoginLockedOutUser -->
